spring.datasource.url=jdbc:postgresql://localhost:5432/greentech_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT - Chave secreta de assinatura
api.security.token.secret=${JWT_SECRET:greentech-chave-secreta-agro-2026}s